"""Generated by Django 5.2.1 on 2025-06-02 14:20."""

from django.db import migrations


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0002_review_specification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="srs",
            new_name="src",
        ),
    ]
