"""Generated by Django 5.2.1 on 2025-06-03 11:37."""

import django.db.models.deletion
import shop._models.category_model
from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0003_rename_srs_productimage_src"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="shop.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="src",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shop._models.category_model.category_image_directory_path,
            ),
        ),
    ]
