"""Generated by Django 5.2.1 on 2025-06-08 09:41."""

from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        (
            "shop",
            "0004_alter_category_options_rename_name_category_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False),
        ),
    ]
