"""Generated by Django 5.2.1 on 2025-06-09 17:08."""

from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0007_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
