"""Generated by Django 5.2.1 on 2025-06-10 14:44."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0008_cart_session_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=25)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        null=True,
                    ),
                ),
                ("delivery_type", models.CharField(max_length=50)),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(default="new", max_length=50),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="orders", to="shop.product"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
