"""Generated by Django 5.2.1 on 2025-06-15 15:29."""

from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0011_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shop.product"),
        ),
    ]
