"""Generated by Django 5.2.1 on 2025-06-21 13:18."""

from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0014_deliverysettings_alter_order_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Доставка"),
                    ("express", "Экспресс-доставка"),
                    ("ordinary", "Обычная доставка"),
                ],
                default="delivery",
                max_length=50,
                verbose_name="Тип доставки",
            ),
        ),
    ]
