"""Generated by Django 5.2.1 on 2025-06-30 10:09."""

from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0018_order_payment_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Уникальный ключ сессии для связи с корзиной/заказом",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Уникальный ключ сессии для связи с корзиной/заказом",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Session Key",
            ),
        ),
    ]
