"""Generated by Django 5.2.1 on 2025-06-30 15:16."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0019_order_session_key_alter_cart_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shop.cart",
                verbose_name="Корзина",
            ),
        ),
    ]
