"""Generated by Django 5.2.1 on 2025-07-02 04:40."""

from django.db import migrations


class Migration(migrations.Migration):

    """Модель миграции."""

    dependencies = [
        ("shop", "0020_order_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="session_key",
        ),
    ]
