# Generated by Django 5.2.1 on 2025-05-28 04:39

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=myauth.models.profile_avatars_directory_path,
            ),
        ),
    ]
